name = "math_from_scratch"
version = "0.1.0"
defaultTargets = ["math_from_scratch"]

[[lean_lib]]
name = "MathFromScratch"

[[lean_exe]]
name = "math_from_scratch"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.33.1"
